config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :registrations, only: [:new,:create,:index] do 
    post 'assign_role'
  end
  resources :tasks, only: [:new,:create,:index] do
    post 'accept_task'
    post 'task_in_progress'
    post 'not_accept_task'
    post 'task_completed'
  end
  resources :roles, only: [:new,:create,:index]
  resources :categories, only: [:new,:create,:index]
  resources :subcategories, only: [:new,:create,:index]
  resources :destinations, only: [:new,:create,:index]
  resources :expenses, only: [:new,:create,:index]
  resources :subcategories, only: [:new,:create,:index]
  resources :destinations
  resources :trips
  resources :sessions, only: [:new, :create] do
    get 'report'
    post 'destroy'
  end
  resources :currencies, only: [:index] do
    get 'convert', on: :collection
    get 'historical_chart', on: :collection
  end
  root to: 'home#index'
  get 'home/task_management', to: 'home#task_management'
  get 'home/expense_tracker', to: 'home#expense_tracker'
  get 'home/currency_converter', to: 'home#currency_converter'
  get 'home/travel_itenary', to: 'home#travel_itenary'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user

  validates :name, :address, presence: true

  before_save :geocode_address

  private

  def geocode_address
    result = Geocoder.search(address).first
    if result
      self.latitude = result.latitude
      self.longitude = result.longitude
    end
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
	belongs_to :category
	belongs_to :subcategory
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :tasks, primary_key: "id", foreign_key: "user_id"
	has_many :destinations
  	has_many :trips
	# attribute :role, :integer, default: 0
	# enum role: { regular: 0, manager: 1, admin: 2 }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def task_management    
  end

  def expense_tracker
    expenses = Expense.all
    @chart_data = expenses.map { |expense| { name: expense.date, data: { expense.date => expense.amount } } }  end

  def currency_converter
  end

  def travel_itenary
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.active = true
    @role.created_at = Time.zone.now
    if @role.save
      session[:user_id] = @role.id
      redirect_to root_path, flash: { success: 'Role Succesfully Created' }
    else
      render :new
    end
  end

  def role_params
    params.require(:role).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/currency_converter.html.erb
<a href=<%= currencies_path %>>Index</a>

app/views/home/expense_tracker.html.erb
<a href=<%= expenses_path %>>All Expenses </a><br><hr>
<a href=<%= new_category_path %>>Create Category </a><br><hr>
<a href=<%= new_subcategory_path %>>Create Sub Category </a><br><hr>
<a href=<%= new_expense_path %>>Create Expense </a><br><hr>
<%= @expenses_array.inspect %>
<%= @formatted_chart_data.inspect %>
<% if @chart_data %>
	<%= column_chart @chart_data, library: { title: { text: 'Historical Exchange Rates' } } %>
<% end %>

app/views/home/index.html.erb
<br>
<br>
<% if current_user.role_id == Role.where(name: "Admin").last.id %>
    <a href=<%= registrations_path %>> Assign role </a><br>
    <a href=<%= new_role_path %>> New Role </a><br>
<% end %>
<a href=<%= home_task_management_path %>>Task Managment </a><br><hr>
<a href=<%= home_expense_tracker_path %>>Expense Tracker </a><br><hr>
<a href=<%= currencies_path %>>Currency Converter </a><br><hr>
<a href=<%= home_travel_itenary_path %>>Travel Iternary </a><br><hr>

app/views/home/task_management.html.erb
<div class="text-center">
  <h1>Task Managment</h1>
  <h1>Welcome <%= current_user.name %></h1>

  <% current_user.tasks.where.not(status: "Task completed").each do |task| %>
    <h2 style="color: red;"><% if task.deadline > Date.today %><%= "Deadline of task #{task.title} in #{(task.deadline - Date.today).to_i} days" %>
      <% else %>
        <%= "Deadline of task #{task.title} has been crossed on #{task.deadline} days" %>
      <% end %>
    </h2>
  <% end %>

  <% if current_user.role_id == 2 %>
    <a href=<%= session_report_path(session[:user_id]) %>> View Report </a><br>
  <% end %>
    <a href=<%= new_task_path %>> Assign Task </a><br>
    <a href=<%= tasks_path %>> View Tasks </a><br>
</div>

app/views/home/travel_itenary.html.erb
<a href=<%= new_destination_path %>>Travel Itenary</a>