config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :registrations, only: [:new,:create,:index] do 
    post 'assign_role'
  end
  resources :tasks, only: [:new,:create,:index] do
    post 'accept_task'
    post 'task_in_progress'
    post 'not_accept_task'
    post 'task_completed'
  end
  resources :roles, only: [:new,:create,:index]
  resources :categories, only: [:new,:create,:index]
  resources :subcategories, only: [:new,:create,:index]
  resources :destinations, only: [:new,:create,:index]
  resources :expenses, only: [:new,:create,:index]
  resources :subcategories, only: [:new,:create,:index]
  resources :destinations
  resources :trips
  resources :sessions, only: [:new, :create] do
    get 'report'
    post 'destroy'
  end
  resources :currencies, only: [:index] do
    get 'convert', on: :collection
    get 'historical_chart', on: :collection
  end
  root to: 'home#index'
  get 'home/task_management', to: 'home#task_management'
  get 'home/expense_tracker', to: 'home#expense_tracker'
  get 'home/currency_converter', to: 'home#currency_converter'
  get 'home/travel_itenary', to: 'home#travel_itenary'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/currency.rb
class Currency < ApplicationRecord
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user

  validates :name, :address, presence: true

  before_save :geocode_address

  private

  def geocode_address
    result = Geocoder.search(address).first
    if result
      self.latitude = result.latitude
      self.longitude = result.longitude
    end
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
	belongs_to :category
	belongs_to :subcategory
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :tasks, primary_key: "id", foreign_key: "user_id"
	has_many :destinations
  	has_many :trips
	# attribute :role, :integer, default: 0
	# enum role: { regular: 0, manager: 1, admin: 2 }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def task_management    
  end

  def expense_tracker
    expenses = Expense.all
    @chart_data = expenses.map { |expense| { name: expense.date, data: { expense.date => expense.amount } } }  end

  def currency_converter
  end

  def travel_itenary
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.active = true
    @role.created_at = Time.zone.now
    if @role.save
      session[:user_id] = @role.id
      redirect_to root_path, flash: { success: 'Role Succesfully Created' }
    else
      render :new
    end
  end

  def role_params
    params.require(:role).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]

	def new
		@task = Task.new
  	@users = User.where(active: true)
	end

	def create
		@task = Task.new(task_params)
		@task.active = true
  	@task.status = "Task created"
  	@task.created_by = current_user.id
    if @task.save
      redirect_to tasks_path, flash: { success: 'Task created successfully' }
    else
      render :new
    end
  end

  def index
  	@task = Task.where(active: true, user_id: current_user.id)
	end

	def accept_task
		@task = Task.where(id: params[:task_id]).update(status: "Task Accepted")
      redirect_to tasks_path, flash: { success: 'Task Accepted successfully' }
	end

	def task_in_progress
		@task = Task.where(id: params[:task_id]).update(status: "Task in progess")
      redirect_to tasks_path, flash: { success: 'Marked Task in progess' }
	end

	def not_accept_task
		@task = Task.where(id: params[:task_id]).update(status: "Task not accept")		
      redirect_to tasks_path, flash: { success: 'Task rejected' }
	end

	def task_completed
		@task = Task.where(id: params[:task_id]).update(status: "Task completed")
      redirect_to tasks_path, flash: { success: 'Task completed successfully' }
	end

  def task_params
    params.require(:task).permit(:title, :description, :deadline, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/roles/new.html.erb
<div class="text-center">
  <h1>New Role</h1>

  <%= form_with(model: @role, url: roles_path, local: true) do |f| %>

    <!-- Field of registration form -->
    <div class='row'>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: 'Please enter name' %>
    </div>

    <div class='row'>
      <%= f.submit 'Create' %>
    </div>
  <% end%>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div><a href="<%= new_task_path %>">Add new task</a></div>
  <% @task.each do |task| %>
    <%= task.title %>
    <%= task.description %>
    <%= task.deadline %><br>

    <% if task.status.downcase == "task created" %>
	    <%= button_to "Task Accept", task_accept_task_path(task), method: :post, class: "btn btn-primary" %>
	    <%= button_to "Task Not Accept", task_not_accept_task_path(task), method: :post, class: "btn btn-danger" %>
    <% end %>
    <% if task.status.downcase == "task accepted" %>
    	<%= button_to "In Progress", task_task_in_progress_path(task), method: :post, class: "btn btn-warning" %>
    <% end %>
    <% if task.status.downcase == "task in progess" %>
    	<%= button_to "Task Completed", task_task_completed_path(task), method: :post, class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="text-center">
  <h1>New Task</h1>

  <%= form_with(model: @task, url: tasks_path, local: true) do |f| %>

    <!-- Field of registration form -->
    <div class='row'>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: 'Please enter task title' %>
    </div>

    <div class='row'>
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: 'Please enter description' %>
    </div>

    <div class='row'>
      <%= f.label :select_user %>
      <%= f.select :user_id, @users.all.collect { |p| [p.name, p.id] }, { include_blank: 'Please enter user' }, { class: 'form-control' } %>

    </div>

    <div class='row'>
      <%= f.label :deadline %>
      <%= f.date_field :deadline, placeholder: 'Please enter deadline of task' %>
    </div>

    <div class='row'>
      <%= f.submit 'Submit' %>
    </div>
  <% end%>
</div>